# Generated by Django 4.0.1 on 2022-02-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_img',
            field=models.URLField(default='default.jpg'),
        ),
    ]
