# Generated by Django 4.0.1 on 2022-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_profile_img_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
