# Generated by Django 4.0.1 on 2022-02-11 11:33

from django.db import migrations
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_slug'),
    ]

def gen_uuid(apps, schema_editor):
    newsstory = apps.get_model('news', 'newsstory')
    for row in newsstory.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_uuid_field'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]