# Generated by Django 4.0.1 on 2022-02-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_populate_uuid_values'),
        ('news', '0006_remove_uuid_null'),
    ]

    operations = [
    ]
