# Generated by Django 4.0.1 on 2022-02-11 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_merge_0005_populate_uuid_values_0006_remove_uuid_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
